"""Added is_active to user model.

Revision ID: 2dce48cbfea6
Revises: cecf8298b202
Create Date: 2017-12-11 18:39:46.343369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dce48cbfea6'
down_revision = 'cecf8298b202'
branch_labels = None
depends_on = None


def upgrade():
    """Add is_active to user table"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    """Remove is_active from user table"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
