"""Include homepage in packages.

Revision ID: 9ee67bf38f1f
Revises: 48dd292b5a80
Create Date: 2017-11-07 15:43:25.825079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ee67bf38f1f'
down_revision = '48dd292b5a80'
branch_labels = None
depends_on = None


def upgrade():
    """TODO: Add an upgrade description."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('homepage', sa.Unicode(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    """TODO: Add a downgrade description."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packages', 'homepage')
    # ### end Alembic commands ###
