"""Added user table.

Revision ID: cecf8298b202
Revises: 9ee67bf38f1f
Create Date: 2017-11-09 16:50:47.759236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cecf8298b202'
down_revision = '9ee67bf38f1f'
branch_labels = None
depends_on = None


def upgrade():
    """TODO: Add an upgrade description."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    """TODO: Add a downgrade description."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
